name: smle
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.13+13

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.5
  flutter_easyloading: ^3.0.5
  flutter_styled_toast: ^2.2.1
  fluttertoast:
#  top_snackbar_flutter: ^3.1.0
  flutter_svg: ^2.0.7
  image_picker: ^1.0.4
  flutter_phoenix: ^1.1.1
  intl: ^0.20.0
  google_fonts: ^6.2.1
  page_transition: ^2.1.0
  freezed_annotation: ^3.1.0
  dio: ^5.3.3
  pretty_dio_logger: ^1.3.1
  get_it: ^8.2.0
#  firebase_core: ^4.0.0
#  firebase_messaging: ^16.0.0
#  flutter_local_notifications: ^19.5.0
  url_launcher: ^6.3.1
  flutter_phone_direct_caller: ^2.2.0
  flutter_widget_from_html_core: ^0.17.0
  # Sign in with google account
  google_sign_in: ^6.2.2
  # Sign in with apple account
  sign_in_with_apple: ^7.0.1
  month_year_picker: ^0.5.0+1
  multiselect: ^0.1.1
  flutter_localizations:
    sdk: flutter
  syncfusion_flutter_pdfviewer: ^31.2.4
  video_player: ^2.10.0
  chewie: ^1.12.1
  fl_chart: ^1.1.1
  hydrated_bloc: ^10.1.1
  path_provider: ^2.1.1
  in_app_purchase: ^3.2.3
  webview_flutter: ^4.13.0
  flutter_paymob: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/png/
    - assets/language/
    - shorebird.yaml

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/png/logo final.png"
  adaptive_icon_background: "#2F3645"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/images/png/logo final.png"
    background_color: "#2F3645"
    theme_color: "#2F3645"
  windows:
    generate: true
    image_path: "assets/images/png/logo final.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/png/logo final.png"
# flutter pub run flutter_launcher_icons
#shorebird release ios
#shorebird patch --platforms=ios