# زيادة Heap للـ Gradle / Kotlin لتفادي خطأ OutOfMemory
org.gradle.jvmargs=-Xmx6144m -Dfile.encoding=UTF-8 -XX:+HeapDumpOnOutOfMemoryError -Dkotlin.daemon.jvm.options="-Xmx4096m"

# تحسين أداء Gradle
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.caching=true

# AndroidX settings
android.useAndroidX=true
android.enableJetifier=true
