// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAinp5glnGf9rhL9G1xLaozbsYgedLFxvM',
    appId: '1:406216784060:web:435d4f7e827bf83533f8b9',
    messagingSenderId: '406216784060',
    projectId: 'smle-gate-18afd',
    authDomain: 'smle-gate-18afd.firebaseapp.com',
    storageBucket: 'smle-gate-18afd.firebasestorage.app',
    measurementId: 'G-50W1V6DEY8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFCeCpIK7ZffMy2r6z41e7IkpheZDn8a8',
    appId: '1:406216784060:android:eff933884c00da1533f8b9',
    messagingSenderId: '406216784060',
    projectId: 'smle-gate-18afd',
    storageBucket: 'smle-gate-18afd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWGudY_XD-fBy7AmGtDa3QM-6dd3C6TDQ',
    appId: '1:406216784060:ios:b79f566f7a41de2733f8b9',
    messagingSenderId: '406216784060',
    projectId: 'smle-gate-18afd',
    storageBucket: 'smle-gate-18afd.firebasestorage.app',
    iosBundleId: 'com.sit.smle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWGudY_XD-fBy7AmGtDa3QM-6dd3C6TDQ',
    appId: '1:406216784060:ios:b79f566f7a41de2733f8b9',
    messagingSenderId: '406216784060',
    projectId: 'smle-gate-18afd',
    storageBucket: 'smle-gate-18afd.firebasestorage.app',
    iosBundleId: 'com.sit.smle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAinp5glnGf9rhL9G1xLaozbsYgedLFxvM',
    appId: '1:406216784060:web:6104e2d6e2dc61dd33f8b9',
    messagingSenderId: '406216784060',
    projectId: 'smle-gate-18afd',
    authDomain: 'smle-gate-18afd.firebaseapp.com',
    storageBucket: 'smle-gate-18afd.firebasestorage.app',
    measurementId: 'G-X0REP7QDNE',
  );
}
